//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiThreadingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicServiceTable
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUIDS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SOURCE { get; set; }
    }
}
